### ISSUE TITLE
This async method lacks 'await' operators

### ISSUE THREAD

**Issue by yallie** [jayonsoftware/apexsharp#1]
Not related to the parser, but I see these warnings in SalesForceAPI project:
```
Db.cs: line 313 This async method lacks 'await' operators and will run synchronously. 
Db.cs: line 323 This async method lacks 'await' operators and will run synchronously. 
Db.cs: line 333 This async method lacks 'await' operators and will run synchronously.
```
The code is located [here](https://github.com/jayonsoftware/apexsharp/blob/master/SalesForceAPI/Db.cs#L313).

I don't see why these methods are implemented in a synchronous way, 
but it looks like they can be fixed simply like this:

```c#
// remove the async modifier
public Task<List<T>> GetAllRecordsAsyncLimit<T>(int limit)
{
    SoqlCreator soql = new SoqlCreator();
    string query = soql.GetSoql<T>();

    query = query + " LIMIT " + limit;
    Console.WriteLine(query);
    return Query<T>(query); // remove .Result
}
```
Not sure if I am missing something?

**Comment by yallie** [comment]
I propose to enable warning as errors, hence the question :)

**Comment by DiegoAngelino** [comment]
I think you have to `await` the method you want to wait,
maybe the `Query<T>` method.

Let me know! :)

**Comment by yallie** [comment]
@DiegoAngelino it works exactly the same:

```c#
public async Task Sample1()
{
     await Task.Delay(TimeSpan.FromSeconds(5));
}

public Task Sample2()
{
     return Task.Delay(TimeSpan.FromSeconds(5));
}
```

**Comment by jayonsoftware** [comment]
Still in development, will fix them

**Comment by DiegoAngelino** [comment]
@Yallie Task works little bit different than Task<T>

Sorry for my typos as sent from my phone.

**Comment by DiegoAngelino** [comment]
@jayonsoftware how have you solved?
