### ISSUE TITLE
Convertor playground

### ISSUE THREAD

**Issue by yallie** [jayonsoftware/apexsharp#13]
While working on the expression translation, I sketched up a toy convertor application.
Enter Apex code in the left text box and watch it converted to C# immediately.
Took about 5-10 minutes to implement, but turned out to be quite helpful:

![image](https://user-images.githubusercontent.com/672878/33236668-84e0de26-d26b-11e7-81ef-52e71ec33af7.png)

To give it a try, set **Playground** project as a startup project and hit F5:

![image](https://user-images.githubusercontent.com/672878/33236676-eac3454e-d26b-11e7-9748-6453923626b5.png)
#

**Comment by jayonsoftware** [comment]
This looks good. Will play with it

**Comment by yallie** [comment]
Added the C# → Apex conversion:

![image](https://user-images.githubusercontent.com/672878/33265879-7441216a-d384-11e7-8273-368eef7c98d8.png)
