### ISSUE TITLE
Failing tests in ApexSharpDemo

### ISSUE THREAD

**Issue by yallie** [jayonsoftware/apexsharp#15]
ApexSharpDemo project has a few failing and/or slow unit tests:

* [ClassRestTest.PostTest](https://github.com/jayonsoftware/apexsharp/blob/master/ApexSharpDemo/CSharpClasses/ClassRestTest.cs#L14) — uses stub API that throws a NotImplementedException
* [ClassUnitTestRunAs.RunAsExample](https://github.com/jayonsoftware/apexsharp/blob/master/ApexSharpDemo/CSharpClasses/ClassUnitTestRunAs.cs#L14) — NUnit requires this method to be public
* [DemoTest. UpdatePhoneTestValidEmail](https://github.com/jayonsoftware/apexsharp/blob/master/ApexSharpDemo/CSharpClasses/DemoTest.cs#L23) — executes a lot of HTTP requests (takes about a minute).

I need to disable these tests or mark as Explicit so they don't break the CI builds.

Can I address these somehow?

**Comment by jayonsoftware** [comment]
sure

**Comment by yallie** [comment]
I currently marked these as Explicit, so they don't run by default.
