### ISSUE TITLE
Upsert is not supported

### ISSUE THREAD

**Issue by tyschacht** [jayonsoftware/apexsharp#16]
I'm trying to pull down an existing apex code set that makes extensive use of upserts.  It does not look like these are supported in the existing Soql implementation.   Is this something on the immediate to-do list?

I'm very interested in this project as I currently do a lot of apex code generation using the SFDC metadata APIs and T4/Razor.   The apex->c# conversion in this project was really close, minus some case inconsistencies and the missing upsert calls.

**Comment by jayonsoftware** [comment]
DId not know many people used Upserts, will add it in the next two days

**Comment by jayonsoftware** [comment]
This has been added also we have moved our Dev to Apexsharp git hub account. Please see https://github.com/apexsharp/apexsharp/blob/dev/Demo/CSharpClasses/DmlTest.cs
