### ISSUE TITLE
Appveyor CI badge in the readme

### ISSUE THREAD

**Issue by yallie** [jayonsoftware/apexsharp#2]
The Appveyor badge in the README.md file points to my copy of the ApexSharp project.
So it currently reflects the build status of my fork, not the original project.

I can't see the settings of your original project, so I can't set proper URL for the badge.
Please have a look at the SETTINGS tab in your Appveyor ApexSharp project.
There is a paragraph called Badges, and it has an item called 'Sample markdown code':

![image](https://user-images.githubusercontent.com/672878/31577029-ccd19f22-b10f-11e7-853e-9a22a0d1669f.png)

Please replace my badge in the readme with your original project badge.
Thanks, Alex

**Comment by jayonsoftware** [comment]
Do I still need to fix this ?

**Comment by yallie** [comment]
That's the thing I can't resolve myself because I can't see your Appveyor project settings.
But of course you can keep it as is if you don't see it as an issue.

The badge currently reports the build status of my own fork.
The fork is synchronized with your main repository on a daily basis.
So, that's not a big deal, a suppose, just a minor issue.

**Comment by yallie** [comment]
Found how to do this and fixed: [here is the instruction](https://help.appveyor.com/discussions/questions/471-infer-badge-url-from-github-user-repo-name).
Generic URL for any github or bitbucket repository can be specified like this:

https://ci.appveyor.com/api/projects/status/[site]/[user]/[project]?svg=true
https://ci.appveyor.com/api/projects/status/github/jayonsoftware/apexsharp?svg=true
