### ISSUE TITLE
Unsupported Apex expressions

### ISSUE THREAD

**Issue by yallie** [jayonsoftware/apexsharp#9]
Here I'm going to collect Apex expressions that don't match the C# syntax.
Supporting these probably requires the full-featured expression parser.
Some of these perhaps can be handled with regular expressions, with limited accuracy.

- [ ] Case insensitivity (method and class names can have arbitrary case in Apex, but not in C#)
- [x] ~[SomeType.class](https://github.com/jayonsoftware/apexsharp/blob/master/ApexParserTest/ApexCSharpClasses/fflib_AnswerTest_CSharp.cs#L23) → typeof(SomeType)~ implemented
- [x] ~string.valueOf(x) → x.ToString()~ implemented with some limitations
- [ ] [Value instanceof SomeType](https://github.com/jayonsoftware/apexsharp/blob/master/ApexParserTest/ApexCSharpClasses/fflib_AnswerTest_CSharp.cs#L58) → Value is SomeType
- [x] ~[new SomeType(Prop1 = expr1, Prop2 = expr2, ...)](https://github.com/jayonsoftware/apexsharp/blob/master/ApexParserTest/ApexTestClasses/SoqlDemo2.cls#L27) → new SomeType { Prop1 = expr1, Prop2 = expr2, ... }~ implemented with some limitations
- [ ] ~SomeAnnotation(Prop1 = expr1 Prop2 = expr2...) → SomeAttribute(Prop1 = expr1, Prop2 = expr2, ...)~ implemented with some limitations

**Comment by jayonsoftware** [comment]
1. We will assume the APEX code we are converting to C# will match cases, for example, System.Debug, no system.debug. 
2. I have not see the usage. You will see code like 
`        String newName = (String)JSON.Deserialize(jsonString, String.class);`
3. Correct
4. Correct
5. Can you give me an example?

**Comment by yallie** [comment]
>5. Can you give me an example?

Here it is:

```apex
@InvocableMethod(label='Get Account Names' description='Returns the list of account names corresponding to the specified account IDs.')
public static List<String> getAccountNames(List<ID> ids) {
   // skipped
}
```

This example is taken [from the official documentation](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_annotation_InvocableMethod.htm).
